### ISSUE TITLE
The browser back button sticky

### ISSUE THREAD

**Issue by summerdrought** [MusikAnimal/wiki-tools#1]
The browser back button needs to be pressed about six times before it returns to the previous page.  This occurs in Firefox, Internet explorer and Safari on my iPad.

**Comment by MusikAnimal** [comment]
Yep, that's a problem alright. A problem I don't know how to fix :( ...yet! Plan to take another stab at it tonight. Thanks

**Comment by MusikAnimal** [comment]
Fixed

**Comment by summerdrought** [comment]
Well done, that was quick!
