### ISSUE TITLE
Make 'pages' URL parameter case-sensitive

### ISSUE THREAD

**Issue by PeterBowman** [MusikAnimal/wiki-tools#2]
All Wiktionaries have the `$wgCapitalLinks` config variable set to false (thus page names are case-sensitive) on most namespaces, see [mw:Manual:$wgCapitalLinks](//www.mediawiki.org/wiki/Manual:$wgCapitalLinks). Since `underscorePageNames()` also converts the first letter to upper case, article names like `bizón` ([link](https://pl.wiktionary.org/wiki/biz%C3%B3n)) won't be handled correctly when passed as a parameter in the URL address.
https://tools.wmflabs.org/musikanimal/pageviews#start=2016-01-08&end=2016-02-07&project=pl.wiktionary.org&platform=all-access&agent=user&pages=biz%C3%B3n
is automatically converted to `Bizón`:
https://tools.wmflabs.org/musikanimal/pageviews#start=2016-01-08&end=2016-02-07&project=pl.wiktionary.org&platform=all-access&agent=user&pages=Biz%C3%B3n

**Comment by MusikAnimal** [comment]
@PeterBowman thanks! You answered the very question I had regarding this. I think I don't actually need to do automatically capitalize for non-wiktionaries even, as I'm now hitting an API endpoint prior to showing the data that normalizes the page names. Just a note there's another related issue with non-English characters. Apparently the pageviews API doesn't want them escaped, so I have another challenge to tackle here. This one is at the top of my list because it's a blocker for many wikis, so expect a fix soon

**Comment by MusikAnimal** [comment]
Actually maybe I was wrong. I think the single fix did the trick... try it now. There is another issue you'll see with `bizón`, where for dates that there's no data it's not represented by zero. This is an API bug, but I think I have a work around

**Comment by PeterBowman** [comment]
It seems to work fine now, thanks :).

**Comment by MusikAnimal** [comment]
@PeterBowman I've moved the tool to [toollabs:pageviews](https://tools.wmflabs.org/pageviews). Are you able to update the [MediaWiki:Histlegend](https://pl.wiktionary.org/wiki/MediaWiki:Histlegend) on pl.wiktionary? Or could you notify them?

I will add a redirect soon, but you should still update the link. This is to unbundle the tool from my Ruby app, as they have nothing to do with each other and if the Ruby app goes down I don't want pageviews to go down too. Additionally the new home at /pageviews conveys that it's a tool for everyone, and not some proprietary product of mine :)

All you need to do here is remove `/musikanimal` from the link. Thanks!

The new repo by the way is at https://github.com/MusikAnimal/pageviews

**Comment by PeterBowman** [comment]
Done! [MediaWiki:Lastmodifiedat](https://pl.wiktionary.org/wiki/MediaWiki:Lastmodifiedat) has been updated, too. It's the timestamp displayed in the footer of every page - an idea borrowed from plWikinews (I have left a notice about the new tool on their Village pump). Apart from that, the folks on plWikipedia have also updated their MediaWiki:Histlegend to point to the new address.
